version: '3'
services:
  hq:
    image: 'surveysolutions/surveysolutions'   
    depends_on:
     - "db"
    environment: 
      ASPNETCORE_ENVIRONMENT: Production
      HQ_ConnectionStrings__DefaultConnection: 'Persist Security Info=true;Server=db;Port=5432;User Id=postgres;Password=pg_password;Database=SurveySolutions'
      HQ_Headquarters__BaseUrl: http://${HQ_HOST}
      HQ_Headquarters__TenantName: default
      Export_ExportSettings__DirectoryPath: /app/AppData/Export
      HQ_Logging__LogsLocation: /app/AppData/logs
    command: []
    volumes:
      - ./data/app:/app/AppData
      - ./data/app.key:/root/.aspnet/DataProtection-Keys
    restart: always

  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: pg_password
    volumes:
      - ./data/database:/var/lib/postgresql/data
    restart: always
