version: '3'
services:

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
        - ./data/backups:/backups
    depends_on:
        - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: SurveySolutions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg_password
      #:  - POSTGRES_PASSWORD_FILE=/run/secrets/db_password <-- alternative for POSTGRES_PASSWORD (to use with docker secrets)
      POSTGRES_EXTRA_OPTS: -Z9 --schema=public --blobs
      SCHEDULE: "@daily"
      BACKUP_KEEP_DAYS: 7
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 6
      HEALTHCHECK_PORT: 8080